export default {
  common: {
    lan: '局域网',
    personalSet: '个人设置',
    shutdown: '关机',
    logout: '注销',
    restart: '重新启动',
    yes: '确定',
    no: '取消',
    desktop: '桌面',
    account: '账号',
    loggingOut: '注销中...',
    home: '主页',
    status: '状态',
    normal: '正常',
    deactivate: '停用',
    refresh: '刷新',
    apply: '应用',
    reset: '重置',
    size: '大小',
    search: '搜索',
    searchResults: '搜索结果',
    operating: '操作',
    items: '个项目',
    pleaseChoose: '请选择',
    enable: '启用',
    disable: '禁用',
    clear: '清除',
    information: '信息',
    previous:'上一步',
    next:'下一步',
    authority:'权限'
  },
  reminder: {
    dataError:'数据获取失败 !',
    notNull: '不能为空',
    userWordLength: '账户长度 3 到 8 位',
    passWordLength: '密码长度 6 到 15 位',
    addGadget: '单击 + 按钮可添加小工具',
    searchError: '搜索错误!',
    changes: '变更尚未保存，您确定要离开吗?',
    userNameError: '用户名校验错误!',
    changeFailed: '信息更改失败!',
    personalAccount: '请输入用户帐号',
    passwordStrength: '最低密码长度为6',
    passwordDifferent: '密码及确认密码不一致,请重新输入',
    legalMailbox: '请输入合法的电子邮件格式',
    userModifyError: '该用户不支持密码编辑',
    InfoSuccess: '信息修改成功',
    pleaseEnterPassword: '请输入密码',
    noUploadedImages: '没有上传的图片',
    pleaseSelectAnImage: '请选择一张图片',
    fileFormatError: '文件格式不正确，请重新上传',
    uploadFailed: '上传失败 !',
    failedToDelete: '删除失败 !',
    chooseToDeleteImg: '请选择要删除的图片',
    confirmDeleteImg: '确认删除该图像 ?',
    messageGettingError: '消息获取错误 !',
    reLogin: '用户密码或语言更改成功，请重新登录',
    desktopMenuError: '桌面加载失败 !',
    userListError: '用户列表获取失败 !',
    NoBlanksAllowed: '字段不允许空白',
    delete: '是否确定要删除 ?',
    folder: '文件夹列表加载失败 !',
    file: '文件列表加载失败 !',
    uploadFileError: '上传文件名称不允许超过40字节 !',
    uploadSizeError: '文件上传不允许超过1G !',
    download: '暂不支持下载大于30m的MP4文件',
    deleteFrequency: '超出访问次数,请稍后再试 !',
    newName: '请输入新的名称',
    newFolder: '请输入文件夹名称',
    nameError: '文件或文件夹名称不可为空',
    nameRex: '名称不允许包含右侧任意字符',
    newNameError: '重命名失败 !',
    createFolderError: '新建文件夹失败 !',
    newNameErrorRex: '当前新建文件夹父文件夹id不能为0 !',
    playError: '播放错误 !',
    getArrayError: '获取存储池数据失败 !',
    getDiskError: '获取硬盘数据失败 !',
    selectPool: '请选择要删除池!',
    deletePool: '是否删除和池有关的联系',
    deletePoolResources: '是否删除所有的池中资源',
    unusedDisk: '获取未使用的硬盘失败 !',
    requiredOption: '确少必要选项 !',
    getLogQuantityError: '获取日志数量失败 !',
    getLogError: '获取日志失败 !',
    username: '您没有输入用户名称',
    authority: '您没有权限执行此操作,请更换账号或向管理员提升权限',
    existed: '用户名存在或被系统保留，请输入另一个名称',
    newUserError: '新增用户失败 !',
    edit: '编辑用户失败 !',
    nicknameExist: '名称已存在,请重新输入',
    socketError:'websocket连接失败 !',
    socketAddress:'websocket地址获取失败 !',
    socketCertification:'websocket认证错误 !',
    loginTimeout:'登陆超时,请重新登陆 !',
    accountOrError:'账号或密码错误，请重新输入',
    userRoot:'注意:普通用户没有权限编辑用户权限',
    notSupport:'此文件夹不支持该操作 !',
    downloadAddressError :'下载文件地址不存在 !',
    fileDownloadFailed:'文件下载失败 !',
    sharedError:'共享根目录下不允许此操作 !',
    userNameRex:'名称不能包含汉字',
    firstLetter:'首字母必须是英文字母',
    userDeactivate:'该账户已停用请联系管理员 !',
    userInfoError:'获取用户信息失败，请重新登陆 !',
    strongError:'强烈建议不要使用条带数据vdev，否则将导致数据丢失!',
    moveError:'移动失败!',
    fixedMenu: '固定菜单失败!',
    networkError:'网络数据加载错误!',
    exportPoolPrompt1:'这些服务取决于池',
    exportPoolPrompt2:' 如果将池分离，则会被破坏：',
    poolExportPrompt:'注意: 导出/断开池错误。',
    poolExportPrompt1:'，导出后，池中的数据将不可用。可以通过设置销毁数据选项来销毁池磁盘上的数据。 在导出/断开连接池之前备份关键数据。',
    destroyPoolData:'销毁这个池里的数据?',
    deletePoolConfig:'删除使用这个池的共享配置?',
    configExport:'确认导出/断开'
  },
  login: {
    username: '用户名',
    password: '密码',
    login: '登录',
    rememberStatus: '记住账户密码'
  },
  desktopMenu: {
    controlPanel: '控制面板',
    fileManagement: '文件管理',
    storageSpace: '存储空间管理',
    logCenter: '日志中心'
  },
  controlMenu: {
    network: '网络',
    user: '用户',
    fileService: '文件服务',
    info: '信息中心',
    fileSharing: '文件共享',
    connectivity: '连接性',
    system: '系统',
    application: '应用程序'
  },
  title: {
    news: '消息',
    options: '选项',
    search: '搜索',
    tool: '工具',
    mainMenu: '主菜单',
    showDesktop: '显示桌面',
    ThereAreNoAlters: '没有消息',
    time: '时间',
    dismissAllAlter: '取消所有更改',
    reOpenAllAlter: '重新打开所有更改',
    userCreationWizard: '新增用户向导',
    resourceMonitor: '资源监控',
    fileManagement: '文件管理',
    monitor: '文件管理监控',
    clearAllItem: '清除已完成项目',
    overview: '总览',
    logOverview:'日志总览',
    source: '源',
    aims: '目标',
    exports: '导出',
    listView: '列表视图',
    tiledView: '平铺视图',
    smallIcon: '小视图',
    middleIcon: '中视图',
    bigIcon: '大视图',
    loading: '加载中',
    assignPermissions:'分配共享文件夹访问权限',
    setPermissions:'设置共享文件夹访问权限',
    settingsAgain:'再次检查设置',
    settingsAgainInfo:'设置想到将会应用下列设置。这个步骤将会花一些时间，请耐心等待。',
    noAccess:'禁止访问',
    readAndWrite:'可读写',
    readOnly:'只读',
    project:'项目',
    value:'数值',
    addGroup:'添加用户分组',
    SuperAdministrator:'系统默认管理员组',
    generalUser:'系统默认组',
    description:'群组说明',
    groupName:'用户组名称',
    join:'加入',
    userGroup:'用户群组',
    serviceName:'服务名称',
    rely:'依赖'
  },
  rightMenu: {
    fixedTaskbar: '固定到任务栏',
    maximize: '最大化',
    minimize: '最小化',
    reduction: '还原',
    shutDown: '关闭',
    unPin: '取消固定'
  },
  systemInfo: {
    systemHealth: '系统信息',
    serverName: '主机名',
    hours: '运行时间',
    base: '基本信息',
    version: '版本',
    productName: '产品名称',
    cpuCores: 'CPU 内核数',
    cpuProcessor: 'CPU 处理器',
    totalMemory: '已安装的总内存',
    processor: '处理器'
  },
  storage: {
    details:'详情',
    compressionRatio:'压缩率',
    compression:'压缩',
    storage: '存储',
    readonly:'只读',
    memorySize: '内存大小',
    used: '已用容量',
    available: '可用容量',
    disk: '磁盘',
    type: '硬盘类型',
    diskInfo: '硬盘信息',
    usedHardDrive: '已用硬盘',
    model: '型号',
    transmissionMode: '传输模式',
    rotatingSpeed: '转速(RPM)',
    HDDSleep: "HDD休眠",
    advanced: '高级电源管理',
    noiseLevel: '噪音等级',
    numbering: '编号',
    pool: '存储池',
    enable: '启用S.M.A.R.T',
    allPool: '所有存储池',
    memoryStatus: '内存状态',
    storageAllocation: '存储分配',
    total: '总容量',
    usageRate: '使用率',
    path: '路径',
    cache: '缓存',
    spare: '备用',
    log: '日志',
    diskDetails: '磁盘详细信息',
    readError: '读取错误',
    writeError: '写入错误',
    selfRepair: '自我修复',
    advancedDetails: '高级详细信息',
    diskSize: '硬盘大小',
    serialNumber: '序列号',
    newDisk: '新增存储池',
    deleteDisk: '删除存储池',
    receive: '接收',
    send: '发送',
    read: '读取',
    standbyMode:'待机状态',
    subsystem:'子系统',
    number:'编号',
    advpowermgmt:'电源管理',
    exportPool:'导出/断开连接池'
  },
  log: {
    latestLog: '最新日志',
    numberOfLogs: '日志数量',
    statistics: '统计',
    by: '通过',
    caveat: '警告',
    prevent: '阻止',
    error: '错误',
    total: '总计',
    lastLogs: '上50个日志',
    operatingStatus: '操作状态',
    logType: '日志类型',
    systemLog: '系统日志',
    onlineUserLog: '线上使用者日志',
    userLog: '使用者日志',
    event: '事件',
    eventDetails: '事件详情',
    notificationRules: '通知规则',
    noticeText: ' 当符合以下任何一种情况时，将给管理员发送通知',
    LogsSecond: '每秒日志数超出',
    severityIs: '严重性为',
    keywordsInclude: '关键字包括',
    PleaseEnterAKeyword: '请输入关键词',
    fileStorageDes: '档案的存储目的地',
    selectedLocation: '选择位置',
    archiveDirectory: '将本地日志归档到先前指定的存储位置',
    archivingRules: '归档规则',
    archiveError: '出现以下事件时，将当前日志数据库归档',
    databaseSize: '数据库大小超过',
    logQuantityLess: '日志数量小于',
    logQuantityBig: '日志数量大于',
    archiveFormat: '归档格式',
    otherArchive: '为其他归档设置启用以下选项',
    defaultFormat: '除默认格式外，将日志以文本格式归档',
    compressLogFiles: '压缩日志档案',
    separateArchive: '根据设备分开归档日志',
    sendLog: '将日志发送至 syslog 服务器',
    position: '位置',
    server: '服务器',
    transferProtocol: '传输协议',
    enableSecurity: '启用安全连接(SSL)',
    importCertificate: '导入证书',
    sendTestLog: '发送测试日志',
    pleaseSelect: '请选择一个共享文件夹',
    serverNameOrIp: '服务器名称或 IP 地址',
    logFormat: '日志格式',
    exportCertificate: '输出证书',
    priorityLevel: '优先层级',
    date_time: '日期&时间'
  },
  search: {
    document: '文档',
    photo: '照片',
    music: '音乐',
    video: '视频',
    all: '全部',
    searchNow: '立即搜索',
    correlationMatch: '相关匹配',
  },
  file: {
    cancelUpload: '取消上传',
    uploadFailed: '上传失败',
    uploadSuccess: '上传成功',
    uploading: '上传中',
    uploadQueue: '已被添加上传队列',
    file: '文件',
    schedule: '进度',
    folder: '文件夹',
    modifiedDate: '修改日期',
    fileType: '文件类型',
    uploadTo: '上传至',
    openInaNewTab: '在新选项卡打开',
    preview: '预览',
    play: '播放',
    rename: '重命名',
    download: '下载',
    createFolder: '新建文件夹',
    allSubFiles: '(所有子文件夹)',
    fileSize: '文件大小',
    creationTime: '创建时间',
    fileFormat: '文件格式',
    upload: '上传',
    uploadFiles: '上传文件',
    enableService: '启用 SMB 服务',
    workgroup: '工作群组',
    pastVersion: '禁止访问以前版本',
    startLog: '启动传输日志',
    logSet: '日志设置',
    viewLog: '查看日志',
    advancedSet: '高级设置',
    note: '注意：',
    noteText1: '在 索引服务 检索文件夹并装载到 Mac 计算机后，您可使用 Finder 来查找所含的文件和内容。',
    noteText: '您可启用 共享文件夹 编辑页面中的回收站',
    noteText2: '启用 高级设置 上的“Bonjour 服务发现”，以帮助 Time Machine 找到共享文件夹。',
    text: '输入以下地址以使用本地网络中的计算机来访问共享文件夹。',
    text1: 'PC(Windows 资源管理器):',
    enableAFP: '启用 AFP 服务',
    enableNFS: '启用 NFS 服务',
    enableNFSStandBy: '启用 NFSv4.1 支持',
    NFSv4: 'NFSv4 域:',
    noteText3: '您可以在 共享文件夹 的编辑页面中编辑共享文件夹的 NFS 权限。'
  },
  netWork: {
    test: '启动本服务后, 用户可通过网络文件协议(NFS)访问系统上的数据.',
    text1: '对于本地地址不使用代理服务器',
    connection: '通过代理服务器连接',
    config: '手动配置 DNS 服务器',
    systemName: '系统名称',
    default: '默认',
    preferred: '首选的 DNS 服务器',
    spare: '备用的 DNS 服务器',
    proxy: '代理服务器',
    address: '地址',
    port: '端口',
    start: '开始',
    end: '结束',
    performance: '性能'
  },
  user: {
    name: '名称',
    description: '描述',
    language: '界面显示语言',
    email: '电子邮箱',
    password: '密码',
    confirmPassword: '确认密码',
    weak: '弱',
    strong: '强',
    in: '中',
    add: '新增',
    newUser: '新增用户',
    edit: '编辑',
    delete: '删除',
    nickName: '昵称',
    userInformation: '用户账号信息',
    infoField: '请填写下方字段',
    whetherToDisable: '是否停用账户'
  },
  desktop: {
    customColor: '自定义颜色',
    textColor: '文字颜色',
    backgroundColor: '背景颜色',
    customWallpaper: '自定义墙纸',
    selectImage: '选择图片',
    myImage: '我的图像',
    defaultWallpaper: '默认壁纸',
    filling: '填充',
    centered: '居中',
    suitable: '最合适的',
    stretch: '伸展',
    tiled: '平铺',
    useMyImage: '使用我的图像',
    myPreviousImage: '我以前的图像',
    deleteSelected: '删除所选图片',
  },
  tabs: {
    userAccount: '用户账号',
    conventional: '常规',
    current: '当前',
    archived: '已存档',
    logFilter: '日志过滤器',
    ram: '内存',
  }
}
