export default {
  common: {
    lan: 'LAN',
    personalSet: 'Personal',
    shutdown: 'Shutdown',
    logout: 'Log Out',
    restart: 'Restart',
    yes: 'Yes',
    no: 'No',
    desktop: 'Desktop',
    account: 'Account',
    loggingOut: 'Logging Out...',
    home: 'Home',
    status: 'Status',
    normal: 'Normal',
    deactivate: 'Deactivate',
    refresh: 'Refresh',
    apply: 'Apply',
    reset: 'Reset',
    size: 'Size',
    search: 'Search',
    searchResults: 'Search results',
    operating: 'Operating',
    items: 'item (s)',
    pleaseChoose: 'Please choose',
    enable: 'Enable',
    disable: 'Disable',
    clear: 'Clear',
    information: 'information',
    previous: 'Previous',
    next: 'Next step',
    authority: 'Authority'
  },
  reminder: {
    dataError:'Data acquisition failed !',
    notNull: 'Can not be empty',
    userWordLength: 'Account length 3 to 8 digits',
    passWordLength: 'Password length 6 to 15 digits',
    addGadget: 'Click the + button to add a gadget',
    searchError: 'Search error',
    changes: 'Changes are not saved. Are you sure you want to leave ?',
    userNameError: 'User name verification error',
    changeFailed: 'Info change failed!',
    personalAccount: 'Please enter user account',
    passwordStrength: 'The minimum password length is 6',
    passwordDifferent: 'Passwords are inconsistent, please re-enter',
    legalMailbox: 'Please enter a legal email format',
    userModifyError: 'This user does not support password editing',
    InfoSuccess: 'Info modified success',
    pleaseEnterPassword: 'Please enter password',
    noUploadedImages: 'No uploaded images',
    pleaseSelectAnImage: 'Please select an image',
    fileFormatError: 'The file format is incorrect, please upload again',
    uploadFailed: 'upload failed !',
    failedToDelete: 'failed to delete !',
    chooseToDeleteImg: 'Please select the picture to delete',
    confirmDeleteImg: 'Are you sure to delete this picture ?',
    messageGettingError: 'Message getting error !',
    reLogin: 'User password or language changed successfully, please log in again',
    desktopMenuError: 'Desktop failed to load !',
    userListError: 'Failed to get user list !',
    NoBlanksAllowed: 'Fields are not allowed to be blank',
    delete: 'Are you sure you want to delete ?',
    folder: 'Failed to load folder list !',
    file: 'File list failed to load !',
    uploadFileError: 'Upload file name cannot exceed 40 bytes !',
    uploadSizeError: 'File uploads are not allowed to exceed 1 G !',
    download: 'Currently does not support downloading MP4 files larger than 30 m',
    deleteFrequency: 'Visits exceeded, delete error !',
    newName: 'Please enter a new name',
    newFolder: 'Please enter a folder name',
    nameError: 'File or folder name cannot be empty',
    nameRex: 'The name cannot contain any characters on the right',
    newNameError: 'Rename failed !',
    createFolderError: 'Failed to create new folder !',
    newNameErrorRex: 'The parent folder id of the current new folder cannot be 0 !',
    playError: 'Playback error !',
    getArrayError: 'Failed to obtain storage pool data !',
    getDiskError: 'Failed to get hard disk data !',
    selectPool: 'Please select the pool to delete!',
    deletePool: 'Whether to delete the connection related to the pool',
    deletePoolResources: 'Whether to delete all resources in the pool',
    unusedDisk: 'Failed to get unused hard disk !',
    requiredOption: 'Really few necessary options !',
    getLogQuantityError: 'Failed to get the number of logs !',
    getLogError: 'Failed to get log !',
    username: 'You did not enter a username',
    authority: 'You do not have the authority to perform this operation, please change the account or raise the authority to the administrator',
    existed: 'User name exists or is reserved by the system, please enter another name',
    newUserError: 'Failed to add user !',
    edit: 'Failed to edit user !',
    nicknameExist: 'Nickname already exists, please re-enter',
    socketError: 'websocket connect failed !',
    socketAddress: 'Failed to obtain websocket address !',
    socketCertification: 'websocket authentication error !',
    loginTimeout: 'Login timed out, please log in again !',
    accountOrError: 'Account or password is wrong, please re-enter',
    userRoot: 'Note: Ordinary users do not have permission to edit user permissions',
    notSupport: 'This folder does not support the operation !',
    downloadAddressError: 'The download file address does not exist',
    fileDownloadFailed: 'File download failed !',
    sharedError: 'This operation is not allowed in the shared root directory',
    userNameRex: 'Username cannot contain Chinese characters',
    firstLetter:'The first letter must be an English letter',
    userDeactivate: 'The account has been disabled, please contact the administrator',
    userInfoError:'Failed to obtain user information, please log in again',
    strongError:'A stripe data vdev is highly discouraged and will result in data loss if it fails !',
    moveError:'Move failed!',
    fixedMenu: 'Fixed menu failed!',
    networkError:'Network data loading error!',
    exportPoolPrompt1:'These services depend on the pool',
    exportPoolPrompt2:'If the pool is separated, it will be destroyed',
    poolExportPrompt:'Note: Export/disconnect pool error.',
    poolExportPrompt1:', After exporting, the data in the pool will be unavailable. You can destroy the data on the pool disk by setting the destroy data option. Back up critical data before exporting/disconnecting the connection pool.',
    destroyPoolData:'Destroy the data in this pool ?',
    deletePoolConfig:'Delete the shared configuration that uses this pool ?',
    configExport:'Confirm export/disconnect'
  },
  login: {
    username: 'Username',
    password: 'Password',
    login: 'Login',
    rememberStatus: 'Remember account password'
  },
  desktopMenu: {
    controlPanel: 'Control Panel',
    fileManagement: 'File Management',
    storageSpace: 'Storage Space',
    logCenter: 'Log Center'
  },
  controlMenu: {
    network: 'Network',
    user: 'User',
    fileService: 'File Service',
    info: 'Info Center',
    fileSharing: 'File Sharing',
    connectivity: 'Connectivity',
    system: 'System',
    application: 'Application'
  },
  title: {
    news: 'News',
    options: 'Options',
    search: 'Search',
    tool: 'Tool',
    mainMenu: 'Main Menu',
    showDesktop: 'Show Desktop',
    ThereAreNoAlters: 'There are no alters',
    time: 'Time',
    dismissAllAlter: 'Dismiss All Alter',
    reOpenAllAlter: 'Re-Open All Alter',
    userCreationWizard: 'User Creation Wizard',
    resourceMonitor: 'Resource Monitor',
    fileManagement: 'File Management',
    monitor: 'File Task Monitor',
    clearAllItem: 'Clear completed items',
    overview: 'Overview',
    logOverview: 'Log overview',
    source: 'Source',
    aims: 'Aims',
    exports: 'Export',
    listView: 'List view',
    tiledView: 'Tiled view',
    smallIcon: 'Small icon',
    middleIcon: 'Middle icon',
    bigIcon: 'Big icon',
    loading: 'Loading',
    assignPermissions: 'Assign shared folder access permissions',
    setPermissions: 'Set shared folder access permissions',
    settingsAgain: 'Check the settings again',
    settingsAgainInfo: 'The settings will apply the following settings. This step will take some time, please be patient.',
    noAccess: 'No Access',
    readAndWrite: 'Read and write',
    readOnly: 'Read only',
    project: 'Project',
    value: 'Value',
    addGroup: 'Add user group',
    SuperAdministrator: 'System default admin group',
    generalUser: 'System default group',
    description: 'description',
    groupName: 'Group name',
    join: 'Join',
    userGroup: 'User group',
    serviceName:'service name',
    rely:'rely'
  },
  rightMenu: {
    fixedTaskbar: 'Fixed Taskbar',
    maximize: 'Maximize',
    minimize: 'Minimize',
    reduction: 'Reduction',
    shutDown: 'Close',
    unPin: 'Pin to Taskbar'
  },
  systemInfo: {
    systemHealth: 'System Health',
    serverName: 'Server Name',
    hours: 'Uptime',
    base: 'Basic Information',
    version: 'Version',
    productName: 'Product Name',
    cpuCores: 'CPU Cores',
    cpuProcessor: 'CPU Processor',
    totalMemory: 'Total Memory',
    processor: 'Processor'
  },
  storage: {
    details:'Details',
    compressionRatio:'Compression ratio',
    compression:'Compression',
    storage: 'Storage',
    readonly:'Readonly',
    memorySize: 'Memory Size',
    used: 'Used capacity',
    available: 'Available capacity',
    disk: 'Disk',
    type: 'Disk Type',
    diskInfo: 'Hard Disk Information',
    usedHardDrive: 'Used hard drive',
    model: 'Model',
    transmissionMode: 'Transfer mode',
    rotatingSpeed: 'Rotating speed(RPM)',
    HDDSleep: "HDD sleep",
    advanced: 'Advanced power management',
    noiseLevel: 'Noise level',
    numbering: 'Numbering',
    pool: 'Storage pool',
    enable: 'Enable S.M.A.R.T',
    allPool: 'All storage pools',
    memoryStatus: 'Memory status',
    storageAllocation: 'Storage allocation',
    total: 'total capacity',
    usageRate: 'Usage rate',
    path: 'Path',
    cache: 'Cache',
    spare: 'Spare',
    log: 'Log',
    diskDetails: 'Disk details',
    readError: 'Read error',
    writeError: 'Write error',
    selfRepair: 'Self-repair',
    advancedDetails: 'Advanced details',
    diskSize: 'Disk Size',
    serialNumber: 'Serial',
    newDisk: 'New storage pool',
    deleteDisk: 'Delete storage pool',
    receive: 'Receive',
    send: 'Send',
    read: 'Read',
    standbyMode:'HDD Standby',
    subsystem:'Subsystem',
    number:'Number',
    advpowermgmt:'advpowermgmt',
    exportPool:'Export/disconnect the connection pool'
  },
  log: {
    latestLog: 'Latest Log',
    numberOfLogs: 'Number of logs',
    statistics: 'Statistics',
    by: 'Pass',
    caveat: 'Caveat',
    prevent: 'Prevent',
    error: 'Error',
    total: 'Total',
    lastLogs: 'Last 50 logs',
    operatingStatus: 'Operating status',
    logType: 'Log type',
    systemLog: 'System log',
    onlineUserLog: 'Online user log',
    userLog: 'User log',
    event: 'Event',
    eventDetails: 'Event details',
    notificationRules: 'Notification rules',
    noticeText: 'When any of the following conditions are met, a notification will be sent to the administrato',
    LogsSecond: 'Logs per second exceeded',
    severityIs: 'The severity is',
    keywordsInclude: 'Keywords include',
    PleaseEnterAKeyword: 'Please enter a keyword',
    fileStorageDes: 'File storage destination',
    selectedLocation: 'Select location',
    archiveDirectory: 'Archive the local log to the previously specified storage location',
    archivingRules: 'Archiving rules',
    archiveError: 'When the following events occur, archive the current log database',
    databaseSize: 'Database size exceeds',
    logQuantityLess: 'The number of logs is less than',
    logQuantityBig: 'The number of logs is greater than',
    archiveFormat: 'Archive format',
    otherArchive: 'Enable the following options for other archive settings',
    defaultFormat: 'In addition to the default format, archive the log in text format',
    compressLogFiles: 'Compress log files',
    separateArchive: 'Separate archive logs according to equipment',
    sendLog: 'Send logs to syslog server',
    position: 'Position',
    server: 'Server',
    transferProtocol: 'Transfer Protocol',
    enableSecurity: 'Enable secure connection(SSL)',
    importCertificate: 'Import certificate',
    sendTestLog: 'Send test log',
    pleaseSelect: 'Please select a shared folder',
    serverNameOrIp: 'Server name or IP address',
    logFormat: 'Log format',
    exportCertificate: 'Export certificate',
    priorityLevel: 'Priority level',
    date_time: 'Date&time'
  },
  search: {
    document: 'Document',
    photo: 'Photo',
    music: 'Music',
    video: 'Video',
    all: 'All',
    searchNow: 'Search',
    correlationMatch: 'Correlation Match'
  },
  file: {
    cancelUpload: 'cancel Upload',
    uploadFailed: 'Upload Failed',
    uploadSuccess: 'Upload Success',
    uploading: 'Uploading',
    uploadQueue: 'Upload queue added',
    file: 'File',
    schedule: 'Schedule',
    folder: 'Folder',
    modifiedDate: 'Modified date',
    fileType: 'File type',
    uploadTo: 'Upload to',
    openInaNewTab: 'Open in a new tab',
    preview: 'Preview',
    play: 'Play',
    rename: 'Rename',
    download: 'Download',
    createFolder: 'Create folder',
    allSubFiles: '(All subfolders)',
    fileSize: 'File Size',
    creationTime: 'Creation Time',
    fileFormat: 'File Format',
    upload: 'Upload',
    uploadFiles: 'Upload files',
    enableService: ' Enable SMB service',
    workgroup: 'Workgroup',
    pastVersion: 'Prohibit access to previous versions',
    startLog: 'Start transfer log',
    logSet: 'Log settings',
    viewLog: 'View log',
    advancedSet: 'advanced settings',
    note: 'Note：',
    noteText1: 'After the indexing service retrieves the folder and mounts it on the Mac computer, you can use the Finder to find the contained files and content',
    noteText: 'You can enable the recycle bin in the shared folder edit page',
    noteText2: 'Enable "Bonjour Service Discovery" on Advanced Settings to help Time Machine find shared folders.',
    text: 'Enter the following address to use a computer on the local network to access the shared folder。',
    text1: 'PC(Windows Explorer):',
    enableAFP: 'Enable AFP service',
    enableNFS: 'Enable NFS service',
    enableNFSStandBy: 'Enable NFSv4.1 support',
    NFSv4: 'NFSv4 domain:',
    noteText3: 'You can edit the NFS permissions of the shared folder on the edit page of the shared folder.'
  },
  netWork: {
    text: 'After starting this service, users can access the data on the system through Network File Protocol (NFS).',
    text1: 'No proxy server for local addresses',
    connection: 'Connect via proxy server',
    config: 'Configure DNS server manually',
    systemName: 'System Name',
    default: 'Default',
    preferred: 'Preferred DNS server',
    spare: 'Alternate DNS server',
    proxy: 'Proxy server',
    address: 'Address',
    port: 'Port',
    start: 'Start',
    end: 'End',
    performance: 'Performance'
  },
  user: {
    name: 'Name',
    description: 'Description',
    language: 'Language',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    weak: 'Weak',
    strong: 'Strong',
    in: 'In',
    add: 'Add',
    newUser: 'New users',
    edit: 'Edit',
    delete: 'Delete',
    nickName: 'NickName',
    userInformation: 'User account information',
    infoField: 'Please fill in the fields below',
    whetherToDisable: 'Whether to deactivate the account'
  },
  desktop: {
    customColor: 'Custom color',
    textColor: 'Text color',
    backgroundColor: 'Background color',
    customWallpaper: 'Custom wallpaper',
    selectImage: 'Select Images',
    myImage: 'My image',
    defaultWallpaper: 'Default wallpaper',
    filling: 'Filling',
    centered: 'Centered',
    suitable: 'Most suitable',
    stretch: 'Stretch',
    tiled: 'Tiled',
    useMyImage: 'Use My Image',
    myPreviousImage: 'My Previous Images',
    deleteSelected: 'Delete selected picture',
  },
  tabs: {
    userAccount: 'User',
    conventional: 'General',
    current: 'Current',
    archived: 'Archived',
    logFilter: 'Log filter',
    ram: 'Memory',
  }
}
